server:
  port: 8001

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka
  instance:
      preferIpAddress: true
      #leaseRenewalIntervalInSeconds: 1
      #leaseExpirationDurationInSeconds: 2
