server:
  port: 5001

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///${GIT_REPO}

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rkomulwad/order-microservice-demo-config-repo